import Foundation

enum DistanceUnit: String, CaseIterable {
    case miles = "mi"
    case kilometers = "km"
    
    var displayName: String {
        switch self {
        case .miles: return "Miles"
        case .kilometers: return "Kilometers"
        }
    }
    
    var shortLabel: String {
        rawValue
    }
    
    func format(_ value: Int) -> String {
        let formatter = NumberFormatter()
        formatter.numberStyle = .decimal
        formatter.groupingSeparator = ","
        formatter.groupingSize = 3
        return (formatter.string(from: NSNumber(value: value)) ?? "\(value)") + " \(rawValue)"
    }
}

struct EventCategory: Hashable, Identifiable {
    let id: String
    let name: String
    let subcategories: [EventSubcategory]
    
    var displayName: String { name }
    
    static let observation = EventCategory(
        id: "observation",
        name: "Observation",
        subcategories: [
            .init(id: "mileage_hour", name: "Mileage/Hour Check", 
                  guidance: "Monitor the distance traveled or hours of operation to track wear and maintenance schedules."),
            .init(id: "damage", name: "Damage", 
                  guidance: "Visually identify any dents, scratches, or structural harm to the vehicle."),
            .init(id: "vibration", name: "Vibration", 
                  guidance: "Notice unusual shaking or movement, often signaling issues with tires, suspension, or drivetrain."),
            .init(id: "noise", name: "Noise", 
                  guidance: "Detect strange sounds such as squealing, grinding, or knocking, which may indicate a mechanical problem."),
            .init(id: "leak_fluid", name: "Leak or Fluid Level", 
                  guidance: "Spot leaking fluids or low levels of essential liquids like oil, coolant, or brake fluid."),
            .init(id: "service_light", name: "Service Engine Light", 
                  guidance: "An indicator that your vehicle's onboard diagnostic system has detected an issue needing attention."),
            .init(id: "error_code", name: "Error Code", 
                  guidance: "Diagnostic codes generated by the vehicle's system, revealing specific issues for troubleshooting."),
            .init(id: "starting", name: "Starting Issue", 
                  guidance: "Difficulty starting the vehicle, often related to the battery, starter, or fuel system."),
            .init(id: "acceleration", name: "Acceleration Problem", 
                  guidance: "Sluggish or inconsistent acceleration, possibly due to engine or transmission trouble."),
            .init(id: "tire_wear", name: "Tire Wear", 
                  guidance: "Uneven or excessive tire tread wear, which can affect safety and efficiency."),
            .init(id: "odor", name: "Unusual Odor", 
                  guidance: "Strange smells, such as burning, fuel, or mold, which may indicate underlying issues."),
            .init(id: "lighting", name: "Lighting Issue", 
                  guidance: "Malfunctions with headlights, brake lights, or interior lighting that affect visibility and safety."),
            .init(id: "battery", name: "Battery Health", 
                  guidance: "The performance and condition of the vehicle's battery, critical for starting and electrical functions."),
            .init(id: "other", name: "Other", 
                  guidance: "Any observations not covered in the above categories.")
        ]
    )
    
    static let repair = EventCategory(
        id: "repair",
        name: "Repair",
        subcategories: [
            .init(id: "wheels_tires_brakes", name: "Wheels, Tires, Brakes", 
                  guidance: "Repairs related to tire replacement, brake pad changes, and wheel alignment."),
            .init(id: "engine", name: "Engine", 
                  guidance: "Fixes for performance issues, overheating, or component failures within the engine."),
            .init(id: "transmission", name: "Transmission", 
                  guidance: "Repairs to address shifting problems or mechanical failures in the drivetrain."),
            .init(id: "radiator", name: "Radiator", 
                  guidance: "Maintenance or replacement to resolve overheating and coolant system issues."),
            .init(id: "suspension", name: "Suspension", 
                  guidance: "Repairs for shocks, struts, or other components affecting ride comfort and stability."),
            .init(id: "steering", name: "Steering", 
                  guidance: "Fixes for issues with power steering, steering alignment, or loose steering mechanisms."),
            .init(id: "electrical", name: "Electrical", 
                  guidance: "Repairs to lights, wiring, sensors, or other electronic systems."),
            .init(id: "body", name: "Body", 
                  guidance: "Bodywork repairs for dents, scratches, or more severe structural damage."),
            .init(id: "exhaust", name: "Exhaust", 
                  guidance: "Fixes for leaks or malfunctions in the exhaust system, affecting emissions and noise."),
            .init(id: "ac_heating", name: "Air Conditioning & Heating", 
                  guidance: "Repairs for climate control systems to restore proper cooling or heating."),
            .init(id: "ignition", name: "Ignition", 
                  guidance: "Fixes for ignition switch, coils, or spark plugs affecting engine startup."),
            .init(id: "glass", name: "Glass", 
                  guidance: "Repairs or replacements for windshields, windows, or mirrors."),
            .init(id: "hybrid_ev", name: "Hybrid/EV Repair", 
                  guidance: "Specific repairs for hybrid or electric vehicle components like batteries or inverters."),
            .init(id: "other", name: "Other", 
                  guidance: "Any repairs not listed in the above categories.")
        ]
    )
    
    static let maintenance = EventCategory(
        id: "maintenance",
        name: "Maintenance",
        subcategories: [
            .init(id: "oil_change", name: "Oil Change", 
                  guidance: "Regular replacement of engine oil to ensure proper lubrication and reduce wear."),
            .init(id: "tire_rotation", name: "Tire Rotation", 
                  guidance: "Repositioning tires to ensure even wear and extend their lifespan."),
            .init(id: "fuel_filter", name: "Fuel Filter", 
                  guidance: "Replacing the fuel filter to keep contaminants out of the fuel system."),
            .init(id: "air_filter", name: "Air Filter", 
                  guidance: "Changing the air filter to ensure optimal airflow to the engine."),
            .init(id: "wiper_blades", name: "Wiper Blades", 
                  guidance: "Replacing worn blades to maintain visibility during adverse weather."),
            .init(id: "brake_fluid", name: "Brake Fluid", 
                  guidance: "Flushing and replacing brake fluid to maintain braking performance."),
            .init(id: "spark_plugs", name: "Spark Plugs", 
                  guidance: "Replacing spark plugs to ensure proper ignition and fuel efficiency."),
            .init(id: "tire_pressure", name: "Tire Pressure", 
                  guidance: "Checking and adjusting tire pressure for safety and fuel efficiency."),
            .init(id: "radiator_coolant", name: "Radiator Coolant", 
                  guidance: "Replacing or topping up coolant to prevent overheating and maintain engine temperature."),
            .init(id: "power_steering", name: "Power Steering", 
                  guidance: "Maintaining power steering fluid to ensure smooth and responsive steering."),
            .init(id: "transmission_fluid", name: "Transmission Fluid", 
                  guidance: "Changing transmission fluid to keep the system lubricated and functioning properly."),
            .init(id: "windshield_fluid", name: "Windshield Fluid", 
                  guidance: "Topping up windshield washer fluid for clear visibility."),
            .init(id: "differential", name: "Differential Lubricant", 
                  guidance: "Replacing differential oil to maintain smooth operation of the drivetrain."),
            .init(id: "belt_chain", name: "Belt/Chain", 
                  guidance: "Inspecting and replacing drive belts or timing chains to avoid engine damage."),
            .init(id: "battery", name: "Battery", 
                  guidance: "Checking and maintaining the battery for reliable starts and consistent electrical performance."),
            .init(id: "wheel_alignment", name: "Wheel Alignment", 
                  guidance: "Ensuring wheels are aligned correctly to improve handling and tire life."),
            .init(id: "hybrid_ev", name: "Hybrid/EV Service", 
                  guidance: "Routine maintenance for hybrid or electric vehicles, including battery checks and software updates."),
            .init(id: "other", name: "Other", 
                  guidance: "Any maintenance not specifically listed above.")
        ]
    )
    
    static let allCategories = [observation, repair, maintenance]
}

struct EventSubcategory: Hashable, Identifiable {
    let id: String
    let name: String
    let guidance: String
    
    var displayName: String { name }
} 