import UIKit
import PDFKit
import UniformTypeIdentifiers

class PDFGenerator {
    static func generateVehiclePDF(_ vehicle: Vehicle) -> URL? {
        // Create PDF document
        let pdfMetaData = [
            kCGPDFContextCreator: "Vehicle App",
            kCGPDFContextAuthor: "Generated by Vehicle App",
            kCGPDFContextTitle: vehicle.displayName
        ]
        let format = UIGraphicsPDFRendererFormat()
        format.documentInfo = pdfMetaData as [String: Any]
        
        let pageWidth = 8.5 * 72.0
        let pageHeight = 11.0 * 72.0
        let pageRect = CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect, format: format)
        
        // Get the documents directory URL
        guard let documentsDirectory = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            return nil
        }
        
        // Create a unique filename
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd-HHmmss"
        let timestamp = dateFormatter.string(from: Date())
        let filename = "\(vehicle.displayName.replacingOccurrences(of: " ", with: "_"))_\(timestamp).pdf"
        let fileURL = documentsDirectory.appendingPathComponent(filename)
        
        do {
            // Generate PDF data
            let pdfData = renderer.pdfData { context in
                context.beginPage()
                let titleFont = UIFont.boldSystemFont(ofSize: 24.0)
                let headerFont = UIFont.boldSystemFont(ofSize: 16.0)
                let textFont = UIFont.systemFont(ofSize: 12.0)
                
                var yPosition: CGFloat = 36.0
                let leftMargin: CGFloat = 36.0
                
                // Title
                vehicle.displayName.draw(at: CGPoint(x: leftMargin, y: yPosition),
                                       withAttributes: [.font: titleFont])
                yPosition += 36.0
                
                // Vehicle Information
                "Vehicle Information".draw(at: CGPoint(x: leftMargin, y: yPosition),
                                        withAttributes: [.font: headerFont])
                yPosition += 24.0
                
                // Use array of tuples to maintain consistent field order
                let details: [(String, String)] = [
                    ("Make", vehicle.make),
                    ("Model", vehicle.model),
                    ("Year", "\(vehicle.year)"),
                    ("Color", vehicle.color),
                    ("Category", getMostSpecificCategory(vehicle)),
                    ("VIN", vehicle.vin ?? "Not specified"),
                    ("Serial Number", vehicle.serialNumber ?? "Not specified"),
                    ("Fuel Type", vehicle.fuelType.displayName),
                    ("Engine Type", vehicle.engineType.displayName),
                    ("Drive Type", vehicle.driveType.displayName),
                    ("Transmission", vehicle.transmissionType.displayName)
                ]
                
                for (key, value) in details {
                    let text = "\(key): \(value)"
                    text.draw(at: CGPoint(x: leftMargin, y: yPosition),
                             withAttributes: [.font: textFont])
                    yPosition += 18.0
                }
                
                if let notes = vehicle.notes {
                    yPosition += 12.0
                    "Notes:".draw(at: CGPoint(x: leftMargin, y: yPosition),
                                withAttributes: [.font: headerFont])
                    yPosition += 24.0
                    notes.draw(at: CGPoint(x: leftMargin, y: yPosition),
                              withAttributes: [.font: textFont])
                    yPosition += 36.0
                }
                
                // Events
                if let events = vehicle.events, !events.isEmpty {
                    "Events".draw(at: CGPoint(x: leftMargin, y: yPosition),
                                withAttributes: [.font: headerFont])
                    yPosition += 24.0
                    
                    for event in events.sorted(by: { $0.date > $1.date }) {
                        let dateStr = event.date.standardFormattedNumeric
                        let typeStr = "\(event.category.displayName) > \(event.subcategory.displayName)"
                        let mileageStr = event.mileage.map { "Mileage: \($0)" } ?? ""
                        let hoursStr = event.hours.map { "Hours: \($0)" } ?? ""
                        let costStr = event.cost.map { "Cost: \($0.formatted(.currency(code: event.currencyCode)))" } ?? ""
                        let detailsStr = event.details ?? ""
                        
                        let eventText = """
                        \(dateStr) - \(typeStr)
                        \(mileageStr)\(mileageStr.isEmpty ? "" : " ")\(hoursStr)\(costStr.isEmpty ? "" : " - \(costStr)")
                        \(detailsStr)
                        """
                        
                        eventText.draw(at: CGPoint(x: leftMargin, y: yPosition),
                                     withAttributes: [.font: textFont])
                        yPosition += 54.0
                        
                        // Start new page if needed
                        if yPosition > pageHeight - 72.0 {
                            context.beginPage()
                            yPosition = 36.0
                        }
                    }
                }
                
                // Ownership Records
                if let records = vehicle.ownershipRecords, !records.isEmpty {
                    if yPosition > pageHeight - 144.0 {
                        context.beginPage()
                        yPosition = 36.0
                    }
                    
                    "Ownership Records".draw(at: CGPoint(x: leftMargin, y: yPosition),
                                          withAttributes: [.font: headerFont])
                    yPosition += 24.0
                    
                    for record in records.sorted(by: { $0.date > $1.date }) {
                        let dateStr = record.date.formatted(date: .numeric, time: .omitted)
                        let typeStr = record.type.displayName
                        let mileageStr = record.mileage.map { "Mileage: \($0)" } ?? ""
                        let hoursStr = record.hours.map { "Hours: \($0)" } ?? ""
                        let costStr = record.cost.map { "Cost: \($0.formatted(.currency(code: record.currencyCode)))" } ?? ""
                        let detailsStr = record.details ?? ""
                        
                        let recordText = """
                        \(dateStr) - \(typeStr)
                        \(mileageStr)\(mileageStr.isEmpty ? "" : " ")\(hoursStr)\(costStr.isEmpty ? "" : " - \(costStr)")
                        \(detailsStr)
                        """
                        
                        recordText.draw(at: CGPoint(x: leftMargin, y: yPosition),
                                      withAttributes: [.font: textFont])
                        yPosition += 54.0
                        
                        // Start new page if needed
                        if yPosition > pageHeight - 72.0 {
                            context.beginPage()
                            yPosition = 36.0
                        }
                    }
                }
            }
            
            // Write to file
            try pdfData.write(to: fileURL)
            
            // Set file attributes for sharing
            try (fileURL as NSURL).setResourceValue(UTType.pdf, forKey: URLResourceKey.contentTypeKey)
            
            return fileURL
        } catch {
            AppLogger.shared.error("Error generating PDF: \(error.localizedDescription)", category: .fileSystem)
            return nil
        }
    }
    
    private static func getMostSpecificCategory(_ vehicle: Vehicle) -> String {
        if let type = vehicle.vehicleType {
            return type.displayName
        }
        if let subcategory = vehicle.subcategory {
            return subcategory.displayName
        }
        return vehicle.category.displayName
    }
} 